iapt-platform/mint

app/dict/dict.js

优化加号拆分的样式，并兼容m,n结尾的自动标准化。标准化列表有待更新

在线巴利词典测试反馈收集 #30

---

app/pali_sent/pali_sent.php

功能函数为 similar_sent_matrix()，从 pali_sent.db3 句子库中逐条读取与所有其他句子进行比较（示例中比较了1000条），将 jaccard_similarity 相似度大于3的 id 号和相似度显示出来。TODO：未完成将结果插入数据库的部分。

:construction:编写了相似句比较的函数

---

app/pali_sent/pali_sent.php

sents_similar_to_id($id) 函数根据句子库中的 id 号，找到相似的句子，函数只比较句子单词长度大于 5 的，计算时间在我的笔记本电脑上大约为 5 秒。
similar_sent_matrix() 函数对相似句进行预计算，策略是找句子单词数相差在3以内的句子进行比较。

:construction:编写了根据id号查找相似的句子的函数，编写了预计算并存入数据库的函数

---

app/studio/js/render.js
documents/users_guide/zh-cn/sent_func.md

用户指南编纂 #20 原文注释

---

app/studio/js/editor.js

🎨 修复编辑框遮挡词典bug

---

app/studio/css/style.css
app/studio/index.php
deploy/install.bat
deploy/multi_process_install/install5.bat

studio页面优化

---

README.md

复制 `<项目目录>/public/app/config.migrate.example.php` 改文件名为`config.migrate.php`
通常这个文件无需修改。只在迁移出现问题，切换pg与sqlite的时候使用。

:memo: public/app/config.migrate.php使用说明

---

README.md

目录遵从Laravel目录设置。有以下几点差别
- public/ 包含旧版php程序的全部文件
- public/tmp 旧版资源文件夹 对于旧版到新版的迁移。**应该将旧版 /tmp 拷贝到 /public**
- v1 旧版数据迁移任务脚本
- deploy 运维代码

:memo: 添加 目录说明

---

public/app/config.sample.php

移动 config.dir.php 到其他设置的下面

---

change-logs.md
public/app/article/article.js
public/app/article/my_article.js
public/app/config.sample.js
public/app/config.sample.php
public/app/db/user.php
public/app/studio/js/index_mydoc.js
public/app/term/note.js
public/app/ucenter/invite.php

- remove WWW_DOMAIN_PROTOCOL WWW_DOMAIN_NAME from config.sample.php
- rename RPC_DOMAIN_NAME -> RPC_SERVER in config.sample.php
- remove WWW_DOMAIN_NAME  from config.sample.js
- rename RPC_DOMAIN_NAME -> RPC_SERVER in config.sample.js

:wrench: remove WWW_DOMAIN_NAME rename RPC_DOMAIN_

---

change-logs.md
composer.json
public/app/config.table.php

- add SnowFlakeDate to config.table.php
- add dependency godruoyi/php-snowflake

⬆️ add dependency godruoyi/php-snowflake

---

public/app/config.sample.php
public/app/dict/dict_lookup.php

配置文件移除多余的
// 雪花id
define("SnowFlake",[
"DatacenterId"=>1,
"WorkerId"=>1
]);

Laravel migrate wbw

---

public/app/studio/editor.php
public/app/studio/js/relation_list.js

list_relation.json rename listrelation.js

:bug: 关系无法连接

---

.gitignore
change-logs.md
public/app/article/function.php
public/app/article/print.css
public/app/term/note.js
public/app/term/term.css
public/app/term/term.js

:art: 优化打印显示效果

---

app/Http/Controllers/DhammaTermController.php
app/Models/DhammaTerm.php
public/app/article/index.php
public/app/article/term.js
public/app/channal/function.php
public/app/wiki/wiki.js
public/app/wiki/wiki.php

#863 :sparkles: term 增加翻译按钮。在阅读器中翻译。

---

public/app/term/term.css
public/app/usent/get.php

:bug: 编辑界面展开更多译文里面的编辑弹出菜单无法显示

---

app/Console/Commands/UpgradePaliText.php

由于内存不够。只返回部分字段

---

app/Console/Commands/UpgradeDaily.php
app/Console/Commands/WebHook.php

:bug: 缺少 Http

---

public/app/group/group.js
public/app/term/note.js

:bug: 编辑模式无法加载

---

public/app/channal/channal.js

:bug: channel列表显示不出来。

---

public/app/term/related_para.js

:bug: 没有相关段落时报错

---

public/app/term/related_para.js
public/app/term/related_para.php

没有相关段落时显示错误

---

public/app/palicanon/category/defualt.json

vinaya 增加 tika子目录

---

public/app/article/article.js
public/app/public/lang/default.json
public/app/public/lang/en.json
public/app/public/lang/my.json
public/app/public/lang/si.json
public/app/public/lang/zh-cn.json
public/app/public/lang/zh-tw.json
public/app/term/note.js

多语言维护 # 908

---

public/app/public/charcode/coverter_my.js
public/app/public/charcode/myanmar.js

罗马到缅文转码函数没有转换数字

---

app/Http/Controllers/SentPrController.php
app/Http/Middleware/EnableCrossRequestMiddleware.php
app/Models/SentPr.php
public/app/article/article.js
public/app/article/index.php
public/app/article/mobile.css
public/app/term/note.js
public/app/usent/function.php

测试项目：
1. pr增加后pr图标数字立即改变
2. pr 可以修改
3. pr 可以删除
4. 句子译文修改是否正常

完成pr 增加，修改，删除

---

app/Console/Kernel.php

使用
```
protected function scheduleTimezone()
{
return 'Asia/Shanghai';
}
```

:fire: timezone()

---

app/Http/Controllers/ChannelController.php
public/app/studio/js/editor.js
routes/api.php

wbw edit 标题显示channel名和用户名

---

public/app/api/controller/user_dicts.php
public/app/dict/dict_lookup.php
public/app/dict/redis_import_user.php
public/app/studio/dict_find_auto.php
public/app/studio/dict_find_one.php
public/app/studio/dict_updata_wbw.php
public/app/term/term.js

输入 [[citta|吉它月]]
显示 吉它月(citta)

术语支持自定义意思显示

---

app/Console/Commands/UpgradePaliText.php
app/Http/Controllers/UserDictController.php
public/app/api/controller/user_dicts.php
public/app/dict/dict_lookup.php
public/app/dict/redis_import_user.php
public/app/studio/dict_find_auto.php
public/app/studio/dict_find_one.php
public/app/studio/dict_updata_wbw.php
public/app/term/note.js
public/app/term/term.js
public/app/usent/sent_pr_merge.php

:bug: 修改建议无法采纳自己的

---

public/app/term/note.js

最大note 嵌套层数改为4

---

documents/proto/article.proto
documents/proto/channel.proto
documents/proto/chapter.proto
documents/proto/course.proto
documents/proto/dictionary.proto
documents/proto/group.proto
documents/proto/public.proto
documents/proto/studio.proto
documents/proto/term.proto
public/app/term/note.js

#992 🐛 句子链接点击问题

---

public/app/term/note.js

:bug: 注释符号位置错误

---

public/app/term/term.css

nissaya展示问题 #997

---

public/app/term/note.js
public/app/users_guide/zh-cn/grammar_my_adv.md
public/app/users_guide/zh-cn/grammar_my_iad.md

nissaya气泡内容与关键字段维护 #894

---

dashboard/src/assets/icon/index.tsx
dashboard/src/components/nut/Home.tsx
dashboard/src/components/nut/WbwTest.tsx
dashboard/src/components/studio/SelectCase.tsx
dashboard/src/components/template/Wbw/WbwCase.tsx
dashboard/src/components/template/Wbw/WbwDetail.tsx
dashboard/src/components/template/Wbw/WbwDetailAdvance.tsx
dashboard/src/components/template/Wbw/WbwDetailBasic.tsx
dashboard/src/components/template/Wbw/WbwDetailBookMark.tsx
dashboard/src/components/template/Wbw/WbwFactorMeaning.tsx
dashboard/src/components/template/Wbw/WbwFactors.tsx
dashboard/src/components/template/Wbw/WbwMeaning.tsx
dashboard/src/components/template/Wbw/WbwMeaningSelect.tsx
dashboard/src/components/template/Wbw/WbwPali.tsx
dashboard/src/components/template/Wbw/WbwWord.tsx
dashboard/src/components/template/Wbw/wbw.css

:art: 调整逐词解析样式与原来的软件一致

---

dashboard/src/components/template/Wbw/WbwCase.tsx
dashboard/src/components/template/Wbw/WbwWord.tsx
dashboard/src/components/template/WbwSent.tsx

有bug
数据是对的。显示结果不对。请 @chonglou 帮忙看一下。

:test_tube: 拆分单词

---

app/Console/Commands/TestMdRender.php
app/Http/Api/TemplateRender.php
app/Http/Controllers/ExportWbwController.php

:bug: 导出wbw 500

---

app/Http/Api/StudioApi.php
app/Http/Controllers/CourseController.php
app/Http/Controllers/CourseMemberController.php
app/Http/Resources/CourseMemberResource.php
app/Http/Resources/CourseResource.php
database/migrations/2023_02_02_135125_add_join_in_courses.php
public/app/api/user.php
public/app/db/user.php

:bug: 紧急修复,无法重置密码

---

dashboard/src/components/api/Term.ts
dashboard/src/components/channel/ChannelSelect.tsx
dashboard/src/components/discussion/DiscussionBox.tsx
dashboard/src/components/general/LangSelect.tsx
dashboard/src/components/general/NissayaCardTable.tsx
dashboard/src/components/template/Term.tsx
dashboard/src/components/term/TermEdit.tsx
dashboard/src/components/term/TermList.tsx

修复术语无法提交的bug

---

app/Http/Controllers/CorpusController.php
app/Http/Resources/TocResource.php

channel 支持两种分隔符 ， _

---

dashboard/src/components/fts/FullTextSearchResult.tsx

add /book-para #1406

---

dashboard/src/components/general/NissayaCardTable.tsx

from: item.from,

---

dashboard/src/components/fts/FtsBookList.tsx
dashboard/src/components/fts/search.css
dashboard/src/pages/library/search/search.tsx

book list改为tree

---

dashboard/src/components/api/Corpus.ts
dashboard/src/components/api/Suggestion.ts
dashboard/src/components/article/ArticleEdit.tsx
dashboard/src/components/article/ArticleView.tsx
dashboard/src/components/article/TypeArticle.tsx
dashboard/src/components/article/TypeArticleReader.tsx
dashboard/src/components/article/TypeArticleReaderToolbar.tsx
dashboard/src/components/auth/setting/SettingArticle.tsx
dashboard/src/components/auth/setting/default.ts
dashboard/src/components/corpus/SentHistory.tsx
dashboard/src/components/template/Builder/ArticleTpl.tsx
dashboard/src/components/template/SentEdit.tsx
dashboard/src/components/template/SentEdit/EditInfo.tsx
dashboard/src/components/template/SentEdit/PrAcceptButton.tsx
dashboard/src/components/template/SentEdit/SuggestionList.tsx
dashboard/src/components/template/Wbw/WbwDetailBasic.tsx
dashboard/src/components/template/Wbw/WbwDetailCase.tsx
dashboard/src/components/template/Wbw/WbwDetailFm.tsx
dashboard/src/components/template/Wbw/WbwDetailOrder.tsx
dashboard/src/locales/en-US/setting/index.ts
dashboard/src/locales/zh-Hans/setting/index.ts

把工具菜单独立成组件

---

dashboard/src/components/dict/DictComponent.tsx
dashboard/src/components/dict/DictContent.tsx
dashboard/src/components/dict/MyCreate.tsx
dashboard/src/components/dict/UserDictList.tsx

#2006 有未保存的脏数据不查词

---

app/Http/Controllers/CourseMemberController.php

add >where('is_current',true) in set_channel

:bug: 绑定channel失败。

---

dashboard/src/components/channel/ChannelMy.tsx
dashboard/src/components/export/ExportModal.tsx

#2138 add search
